name: Gitleaks Secret Scan
on:
  pull_request:
    branches:
      - '**' # Run on pull requests for all branches
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Run Gitleaks
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v1.4.0
        with:
          config: "" # Optional: You can specify a custom Gitleaks config file
          verbose: true
          redacted: true
          fail: true # Fails the workflow if secrets are detected
      # Upload results (optional)
      - name: Upload scan results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks.log
